spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:hsqldb:file:db/hotel;hsqldb.lock_file=false
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true