spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/spring-hotel
    username: hotel-admin
    password: admin
    data: classpath:data-mysql.sql
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    com:
      vahundos:
        DEBUG